- name: install required pacakges (Debian)
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - apache2
    - mysql-server
    - php5
    - php5-mysql
    - python-mysqldb
  when: ansible_os_family == "Debian"

- name: Create database
  action: copy src=keybase.sql dest=/tmp/keybase.sql

- name: create or recreate keybase DB (existing data is lost)
  shell: "{{item}}"
  with_items:
    - "mysql -u root -e 'DROP DATABASE IF EXISTS keybase'"
    - "mysql -u root -e 'CREATE DATABASE keybase'"
    - "mysql -u root keybase < /tmp/keybase.sql"
  tags:
    - createdb

- name: create directory
  file: path=/var/www/dbpages/lib state=directory owner=root group=root

# keybase code
- name: extract keybase code 
  action: unarchive src=keybase.tar dest=/var/www/dbpages/ owner=root group=root
 
- name: Copy CodeIgniter files (Debian)
  action: unarchive src=CodeIgniter_2.1.4.tar dest=/var/www/dbpages/lib owner=root group=root

- name: Copy proxy config to sites-available
  copy: src=keybase.conf dest=/etc/apache2/sites-available/ owner=root group=root

- name: Copy proxy config to sites-available 
  command: "rm -f /etc/apache2/sites-enabled/*"
  ignore_errors: yes

- name: Enable keybase site 
  command: a2ensite keybase.conf
  when: ansible_os_family == "Debian"

- name: Enable mod rewrite (Debian)
  command: a2enmod rewrite
  when: ansible_os_family == "Debian"

- name: Start Apache2 (Debian)
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian" 
