- name: restart mysql
  service: name={{mysql_service}} state=restarted

- name: restart tomcat
  service: name={{tomcat}} state=restarted

- name: restart httpd
  service: name={{apache}} state=restarted

- name: restart apache
  service: name={{apache}} state=restarted