
- hosts: biocache
  roles:
    - common
    - java
    - cassandra3
    - nameindex
    - { role: biocache-db,      use_cassandra3 : true }
    - biocache-properties
    - nameindex
    - { role: biocache-cli,     biocache_cli_version: "2.2" }
    - jenkins
    - apache