# assets
version: "{{ profile_service_version | default('LATEST') }}"
artifactId: "profile-service"
classifier: ''
packaging: "war"
groupId: "au.org.ala"
profile_service_war_url: "{{maven_repo_ws_url}}"
